In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
mylist

[1, 2, 3]

In [7]:
myarr = np.array(mylist)

In [8]:
type(myarr)

numpy.ndarray

In [10]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [11]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

In [22]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [29]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
np.ones((1,4))l

array([[1., 1., 1., 1.]])

In [38]:
np.linspace(0,10,12)

array([ 0.        ,  0.90909091,  1.81818182,  2.72727273,  3.63636364,
        4.54545455,  5.45454545,  6.36363636,  7.27272727,  8.18181818,
        9.09090909, 10.        ])

In [40]:
np.eye(7)    

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [50]:
np.random.rand(5,2)

array([[0.13829335, 0.6381396 ],
       [0.09960749, 0.78396624],
       [0.39591189, 0.99343239],
       [0.67639604, 0.33836873],
       [0.7206826 , 0.87453202]])

In [54]:
np.random.randn(2,3)

array([[-0.23720857,  0.04996928, -0.53343519],
       [ 0.56984316, -0.10420332,  0.09571605]])

In [70]:
np.random.randint(0,101,10)

array([48, 10, 72, 92, 85, 47, 49, 28, 29, 95])

In [75]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [76]:
arr = np.arange(0,25)

In [81]:
arr.reshape((5,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [94]:
ranarr = np.random.randint(0,101,10)

In [95]:
ranarr

array([ 6, 20, 72, 38, 17,  3, 88, 59, 13,  8])

In [96]:
ranarr.max()

88

In [97]:
ranarr.min()

3

In [98]:
ranarr.argmin()

5

In [99]:
ranarr.argmax()

6

In [100]:
ranarr.dtype

dtype('int32')

In [101]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [102]:
arr.shape

(25,)

In [104]:
arr = arr.reshape(5,5)

In [105]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [108]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [109]:
arr = np.arange(0,11)

In [110]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [111]:
arr[8]

8

In [114]:
arr[:5]

array([0, 1, 2, 3, 4])

In [115]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [116]:
arr[0:5]=100

In [117]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [118]:
arr = np.arange(0,11)

In [119]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [121]:
slice_of_arr = arr[0:5]

In [122]:
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [123]:
slice_of_arr[:]=99

In [124]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [125]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [126]:
arr_copy = arr.copy()

In [127]:
arr_copy[:] = 100

In [128]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [129]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [133]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [134]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [135]:
arr_2d.shape

(3, 3)

In [142]:
arr_2d[0,2]

15

In [144]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [145]:
arr = np.arange(1,11)

In [146]:
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [147]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [148]:
bool_arr = arr > 4

In [149]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [150]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [151]:
arr = np.arange(0,10)

In [152]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [153]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [154]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [155]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [156]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [157]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [158]:
arr / arr

C:\Users\JohnS\AppData\Local\Temp\ipykernel_14052\3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [159]:
1 / 0 

ZeroDivisionError: division by zero

In [160]:
1 / arr[0]

C:\Users\JohnS\AppData\Local\Temp\ipykernel_14052\2460598279.py:1: RuntimeWarning: divide by zero encountered in long_scalars
  1 / arr[0]


inf

In [161]:
1 / arr

C:\Users\JohnS\AppData\Local\Temp\ipykernel_14052\1528351372.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [162]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [163]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [164]:
np.log(arr)

C:\Users\JohnS\AppData\Local\Temp\ipykernel_14052\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [165]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [166]:
arr.sum()

45

In [167]:
arr.mean()

4.5

In [168]:
arr.mode()

AttributeError: 'numpy.ndarray' object has no attribute 'mode'

In [169]:
arr.med()

AttributeError: 'numpy.ndarray' object has no attribute 'med'

In [170]:
arr.std()

2.8722813232690143

In [171]:
arr.var()

8.25

In [172]:
arr.max()

9

In [176]:
arr_2d = np.arange(0,25).reshape(5,5)

In [177]:
arr_2d.sum()

300

In [180]:
arr_2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [179]:
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [181]:
arr_2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])